# Generated by Django 4.0.10 on 2023-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

# migrations are a way of propagating changes made to your models
# (like adding a field, deleting a model, etc.) into your database schema.

# what will happen if there is a name field in the model and there are some data
# in the database has the name field originally and i delete the name field and
# mirgate the model to the database? will those data processing the name field be altered?
# -----------------------------------------------------------------------------------------
# If you delete a field from your Django model and then create and apply a migration,
# Django will generate a migration to delete the corresponding column from the relevant
# database table. When the migration is applied with python manage.py migrate,
# the database column for that field will be deleted.

# what if i add a new field and those data in the database didnt have that field before?
# -----------------------------------------------------------------------------------------
# If you specify a default value when adding the field to your model
# (for example, new_field = models.IntegerField(default=0)), then this
# default value will be added to all existing rows in the new column.

# If you don't specify a default value and the field is not nullable
# (i.e., null=False, which is the default setting), Django will raise
# an error when you try to make the migration.

# If you don't specify a default value, but the field is nullable
# (i.e., null=True), then Django will add the new column and fill
# it with null values for all existing rows.